name: Publish NuGet Package

on:
  push:
    branches:
      - main # Trigger only on pushes to the main branch
env:
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}\output

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Setup .NET
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x' # Adjust to your project's SDK version
    
    # Step 3: Install dependencies and build the project
    - name: Restore dependencies
      run: dotnet restore TestLibrary/TestLibrary/TestLibrary.csproj
      
    - name: Build the project
      run: dotnet build TestLibrary/TestLibrary/TestLibrary.csproj --configuration Release

    - name: Pack the project into a NuGet package
      run: dotnet pack TestLibrary/TestLibrary/TestLibrary.csproj --configuration Release --no-build --output ./bin/Release

    - name: Push NuGet package to GitHub Packages
      run: |
          dotnet nuget push ./bin/Release/*.nupkg \
            --source "https://nuget.pkg.github.com/${{ secrets.OWNER }}/index.json" \
            --api-key ${{ secrets.NUGET_TOKEN }}
      env:
          NUGET_API_KEY: ${{ secrets.NUGET_TOKEN }}
